import { REQUEST } from '@nestjs/core';

export const EVENT_LISTENER_METADATA = 'EVENT_LISTENER_METADATA';
export const EVENT_PAYLOAD = REQUEST;
export const EVENT_EMITTER_MODULE_OPTIONS = Symbol(
  'EVENT_EMITTER_MODULE_OPTIONS',
);
